// File generated by FlutterFire CLI.
// TODO: Replace with actual firebase_options.dart generated by running:
//   flutterfire configure
//
// This is a placeholder so the project compiles.
// Run `flutterfire configure` to generate the real file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4-nxkhjBvUBBUPqOXyalxwAWUMvc1jA',
    appId: '1:496747365744:android:ae4f81335d91e1b057bbb5',
    messagingSenderId: '496747365744',
    projectId: 'coffeeno',
    storageBucket: 'coffeeno.firebasestorage.app',
  );

  // TODO: Replace these placeholder values with your Firebase project config

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAuHgyMG4dTqEBUWzZIWZzShwtTXZOMs',
    appId: '1:496747365744:ios:bab21e85bc29970257bbb5',
    messagingSenderId: '496747365744',
    projectId: 'coffeeno',
    storageBucket: 'coffeeno.firebasestorage.app',
    iosClientId: '496747365744-2hjqvr4p9cplv0n05iffjvjktf90cqq4.apps.googleusercontent.com',
    iosBundleId: 'com.coffeeno.coffeeno',
  );

}